# ===============================================
# Robot (Follower) Configuration
# ===============================================
robot:
  # Specifies which subclass of RobotConfig to use.
  # This matches the name in `@RobotConfig.register_subclass("supre_robot_follower")`
  type: sim_robot_hil

#hil new fields
  #urdf_path: "/home/smai/workspace/dikeke/webxr/urdf/RJ2506-20251125-all-13-std.urdf"
  #urdf_path: "/home/smai/workspace/dc_dir/sim_lerobot/rf2502_new_3/urdf/rf2502_new_3.urdf"
  #urdf_path1: "/home/smai/workspace/dc_dir/sim_lerobot/rf2502_new_3/urdf/rf2502_new_3.urdf"
  urdf_path: "/home/smai/workspace/dikeke/webxr/supre_robot/rf2502_new_3_std.urdf"
  urdf_path1: "/home/smai/workspace/dikeke/webxr/supre_robot/rf2502_new_3_std.urdf"
  target_frame_name: arml_Link5
  end_effector_bounds:
    min:
      - -10.0
      - -10.0
      - -10.0
    max:
      - 10.0
      - 10.0
      - 10.0
  end_effector_step_sizes:
    x: 1.0
    y: 1.0
    z: 1.0

teleop:
  # Specifies which subclass of TeleoperatorConfig to use.
  # This matches the name in `@TeleoperatorConfig.register_subclass("supre_robot_leader")`
  type: webxr
  zenoh_connect_key: "tcp/47.116.8.214:7447"
# ===============================================
# Control Configuration
# ===============================================
fps: 30
robot_type: "sim_robot_hil"
# Teleoperation duration in seconds (null = unlimited)
teleop_time_s: null