output_dir: null
job_name: default
resume: false
seed: 1000
num_workers: 4
batch_size: 256
steps: 100000
log_freq: 500
save_checkpoint: true
save_freq: 2000000
wandb:
  enable: true
  project: supre_robot_real
  disable_artifact: true
dataset:
  repo_id: hf_username/dataset_name
  use_imagenet_stats: false
policy:
  type: sac
  n_obs_steps: 1
  repo_id: hf_username/policy_name
  normalization_mapping:
    VISUAL: MEAN_STD
    STATE: MIN_MAX
    ENV: MIN_MAX
    ACTION: MIN_MAX
  input_features:
    observation.images.left_wrist_cam:
      type: VISUAL
      shape:
        - 3
        - 128
        - 128
    observation.images.head_cam:
      type: VISUAL
      shape:
        - 3
        - 128
        - 128
    observation.state:
      type: STATE
      shape:
        - 15
  device: cuda
  use_amp: false
  dataset_stats:
    observation.images.head_cam:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225
    observation.images.left_wrist_cam:
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225
    observation.state:
      min:
        - -15.0
        - -20.0
        - 10.0
        - 65.0
        - 0.0
        - 0.0
        - -40.0
        - -60.0
        - -50.0
        - -80.0
        - -10.0
        - -110.0
        - -15.0
        - -20.0
        - 15.0
        - 70.0
        - -5.0
        - 0.0
        - 0.26
        - -0.06
        - 0.25
      max:
        - 15.0
        - 15.0
        - 40.0
        - 110.0
        - 0.5
        - 31.0
        - 53.0
        - 61.0
        - 67.0
        - 90.0
        - 6.0
        - 100.0
        - 15.0
        - 12.0
        - 40.0
        - 110.0
        - 0.5
        - 31.0
        - 0.32
        - 0.06
        - 0.35
    action:
      min:
        - -0.03
        - -0.03
        - -0.03
      max:
        - 0.03
        - 0.03
        - 0.03
  num_discrete_actions: 3
  storage_device: cuda
  vision_encoder_name: helper2424/resnet10
  freeze_vision_encoder: true
  image_encoder_hidden_dim: 32
  shared_encoder: true
  online_steps: 1000000
  online_env_seed: 10000
  online_buffer_capacity: 30000
  offline_buffer_capacity: 10000
  online_step_before_learning: 100
  policy_update_freq: 1
  discount: 0.97
  async_prefetch: false
  temperature_init: 0.01
  num_critics: 2
  num_subsample_critics: null
  critic_lr: 0.0003
  actor_lr: 0.0003
  temperature_lr: 0.0003
  critic_target_update_weight: 0.005
  utd_ratio: 2
  state_encoder_hidden_dim: 256
  latent_dim: 256
  target_entropy: null
  use_backup_entropy: true
  grad_clip_norm: 40.0
  critic_network_kwargs:
    hidden_dims:
      - 256
      - 256
    activate_final: true
    final_activation: null
  actor_network_kwargs:
    hidden_dims:
      - 256
      - 256
    activate_final: true
  policy_kwargs:
    use_tanh_squash: true
    std_min: -5
    std_max: 2
    init_final: 0.05
  actor_learner_config:
    learner_host: 127.0.0.1
    learner_port: 50051
    policy_parameters_push_frequency: 4
  concurrency:
    actor: threads
    learner: threads
env:
  type: gym_manipulator
  robot:
    # Specifies which subclass of RobotConfig to use.
    # This matches the name in `@RobotConfig.register_subclass("supre_robot_follower")`
    type: supre_robot_follower_hil
  
  #hil new fields
    urdf_path: "/home/t/workspace/gitprj/lerobot-env/supre_robot_urdf/RJ2506-20251125-all-13-std.urdf"
    target_frame_name: left_hand_base
    end_effector_bounds:
      min:
        - -1.0
        - -1.0
        - -1.0
      max:
        - 1.0
        - 1.0
        - 1.0
    end_effector_step_sizes:
      x: 0.025
      y: 0.025
      z: 0.025  
    # Path to the joint configuration file for the follower robot.
    # Corresponds to: SupreRobotFollowerConfig.joint_config_path
    joint_config_file: "trunk_config_supre_robot_follower_joint_hil.yaml"
    # Dictionary of camera configurations.
    # Corresponds to: cameras: dict[str, CameraConfig]
    cameras: 
      head_cam:
        type: opencv
        index_or_path: 1
        width: 640
        height: 480
        fps: 30
      left_wrist_cam:
        type: opencv
        index_or_path: 5
        width: 640
        height: 480
        fps: 30
  
    # Maximum relative joint movement in degrees per control step.
    # Corresponds to: max_relative_joint_move: float
    max_relative_joint_move: 10.0 #30.0
  
    # Port for the Prometheus monitoring server. Use `null` for None.
    # Corresponds to: prometheus_port: int | None
    prometheus_port: 8000
  
    # Control loop frequency in Hz.
    # Corresponds to: control_frequency: int
    control_frequency: 30
  
    # List of motor calibration settings for each joint.
    # Corresponds to: calibration: list[MotorCalibration]
    calibration:
      # --- Left Arm ---
      - joint_name: "left_arm_joint_1"
        min_position: -160.0
        max_position: 160.0
      - joint_name: "left_arm_joint_2"
        min_position: -90.0
        max_position: 0.0
      - joint_name: "left_arm_joint_3"
        min_position: -150.0
        max_position: 150.0
      - joint_name: "left_arm_joint_4"
        min_position: -90.0
        max_position: 0.0
      - joint_name: "left_arm_joint_5"
        min_position: -150.0
        max_position: 150.0
      - joint_name: "left_arm_joint_6"
        min_position: -90.0
        max_position: 90.0
      - joint_name: "left_arm_joint_7"
        min_position: 0.0
        max_position: 1.0
  teleop:
    # Specifies which subclass of TeleoperatorConfig to use.
    # This matches the name in `@TeleoperatorConfig.register_subclass("supre_robot_leader")`
    type: supre_robot_leader
  
    # Path to the joint configuration file for the leader robot.
    # Corresponds to: SupreRobotLeaderConfig.joint_config_path
    joint_config_file: "trunk_config_supre_robot_leader_joint_hil.yaml"
  
    # Direction multipliers for each joint.
    # Corresponds to: joint_direction: list
    joint_direction:
      - -1
      - -1
      - 1
      - 1
      - 1
      - -1
      - 1
  wrapper:
    display_cameras: false
    add_joint_velocity_to_observation: true
    add_current_to_observation: true
    add_ee_pose_to_observation: true
    crop_params_dict:
      observation.images.head_cam:
        - 270
        - 170
        - 90
        - 190
      observation.images.left_wrist_cam:
        - 0
        - 0
        - 480
        - 640
    resize_size:
      - 128
      - 128
    control_time_s: 20.0
    use_gripper: true
    gripper_quantization_threshold: null
    gripper_penalty: -0.02
    gripper_penalty_in_reward: false
    fixed_reset_joint_positions:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    reset_time_s: 2.5
    control_mode: leader
  name: real_robot
  #mode record/replay
  mode: record
  repo_id: null
  dataset_root: null
  task: ""
  num_episodes: 2
  episode: 0
  pretrained_policy_name_or_path: null
  device: cpu
  push_to_hub: false
  fps: 20
  features:
    observation.images.head_cam:
      type: VISUAL
      shape:
        - 3
        - 128
        - 128
    observation.images.left_wrist_cam:
      type: VISUAL
      shape:
        - 3
        - 128
        - 128
    observation.state:
      type: STATE
      shape:
        - 15
    action:
      type: ACTION
      shape:
        - 3
  features_map:
    observation.images.head_cam: observation.images.head_cam
    observation.images.left_wrist_cam: observation.images.left_wrist_cam
    observation.state: observation.state
    action: action
  reward_classifier_pretrained_path: null